// ActionTypes.js

export const CREATE_TOOL_ITEM_REQUEST = 'CREATE_TOOL_ITEM_REQUEST';
export const CREATE_TOOL_ITEM_SUCCESS = 'CREATE_TOOL_ITEM_SUCCESS';
export const CREATE_TOOL_ITEM_FAILURE = 'CREATE_TOOL_ITEM_FAILURE';

export const GET_TOOL_ITEMS_BY_TOOLOWNER_ID_REQUEST =
  'GET_TOOL_ITEMS_BY_TOOLOWNER_ID_REQUEST';
export const GET_TOOL_ITEMS_BY_TOOLOWNER_ID_SUCCESS =
  'GET_TOOL_ITEMS_BY_TOOLOWNER_ID_SUCCESS';
export const GET_TOOL_ITEMS_BY_TOOLOWNER_ID_FAILURE =
  'GET_TOOL_ITEMS_BY_TOOLOWNER_ID_FAILURE';

export const DELETE_TOOL_ITEM_REQUEST = 'DELETE_TOOL_ITEM_REQUEST';
export const DELETE_TOOL_ITEM_SUCCESS = 'DELETE_TOOL_ITEM_SUCCESS';
export const DELETE_TOOL_ITEM_FAILURE = 'DELETE_TOOL_ITEM_FAILURE';

export const SEARCH_TOOL_ITEM_REQUEST = 'SEARCH_TOOL_ITEM_REQUEST';
export const SEARCH_TOOL_ITEM_SUCCESS = 'SEARCH_TOOL_ITEM_SUCCESS';
export const SEARCH_TOOL_ITEM_FAILURE = 'SEARCH_TOOL_ITEM_FAILURE';

export const UPDATE_TOOL_ITEMS_AVAILABILITY_REQUEST = 'UPDATE_TOOL_ITEMS_AVAILABILITY_REQUEST';
export const UPDATE_TOOL_ITEMS_AVAILABILITY_SUCCESS = 'UPDATE_TOOL_ITEMS_AVAILABILITY_SUCCESS';
export const UPDATE_TOOL_ITEMS_AVAILABILITY_FAILURE = 'UPDATE_TOOL_ITEMS_AVAILABILITY_FAILURE';
// ActionType.js
export const GET_ALL_TOOL_ITEMS_REQUEST = "GET_ALL_TOOL_ITEMS_REQUEST";
export const GET_ALL_TOOL_ITEMS_SUCCESS = "GET_ALL_TOOL_ITEMS_SUCCESS";
export const GET_ALL_TOOL_ITEMS_FAILURE = "GET_ALL_TOOL_ITEMS_FAILURE";
