// ActionTypes.js

export const CREATE_TOOLOWNER_REQUEST = "CREATE_TOOLOWNER_REQUEST";
export const CREATE_TOOLOWNER_SUCCESS = "CREATE_TOOLOWNER_SUCCESS";
export const CREATE_TOOLOWNER_FAILURE = "CREATE_TOOLOWNER_FAILURE";

export const GET_ALL_TOOLOWNERS_REQUEST = "GET_ALL_TOOLOWNERS_REQUEST";
export const GET_ALL_TOOLOWNERS_SUCCESS = "GET_ALL_TOOLOWNERS_SUCCESS";
export const GET_ALL_TOOLOWNERS_FAILURE = "GET_ALL_TOOLOWNERS_FAILURE";

export const DELETE_TOOLOWNER_REQUEST = "DELETE_TOOLOWNER_REQUEST";
export const DELETE_TOOLOWNER_SUCCESS = "DELETE_TOOLOWNER_SUCCESS";
export const DELETE_TOOLOWNER_FAILURE = "DELETE_TOOLOWNER_FAILURE";

export const UPDATE_TOOLOWNER_REQUEST = "UPDATE_TOOLOWNER_REQUEST";
export const UPDATE_TOOLOWNER_SUCCESS = "UPDATE_TOOLOWNER_SUCCESS";
export const UPDATE_TOOLOWNER_FAILURE = "UPDATE_TOOLOWNER_FAILURE";

export const GET_TOOLOWNER_BY_ID_REQUEST = "GET_TOOLOWNER_BY_ID_REQUEST";
export const GET_TOOLOWNER_BY_ID_SUCCESS = "GET_TOOLOWNER_BY_ID_SUCCESS";
export const GET_TOOLOWNER_BY_ID_FAILURE = "GET_TOOLOWNER_BY_ID_FAILURE";

export const GET_TOOLOWNER_BY_USER_ID_REQUEST =
  "GET_TOOLOWNER_BY_USER_ID_REQUEST";
export const GET_TOOLOWNER_BY_USER_ID_SUCCESS =
  "GET_TOOLOWNER_BY_USER_ID_SUCCESS";
export const GET_TOOLOWNER_BY_USER_ID_FAILURE =
  "GET_TOOLOWNER_BY_USER_ID_FAILURE";

export const UPDATE_TOOLOWNER_STATUS_REQUEST =
  "UPDATE_TOOLOWNER_STATUS_REQUEST";
export const UPDATE_TOOLOWNER_STATUS_SUCCESS =
  "UPDATE_TOOLOWNER_STATUS_SUCCESS";
export const UPDATE_TOOLOWNER_STATUS_FAILURE =
  "UPDATE_TOOLOWNER_STATUS_FAILURE";

  export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
  export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
  export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

  export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
  export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
  export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

  export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
  export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
  export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

  export const GET_TOOLOWNERS_EVENTS_REQUEST = "GET_TOOLOWNERS_EVENTS_REQUEST";
  export const GET_TOOLOWNERS_EVENTS_SUCCESS = "GET_TOOLOWNERS_EVENTS_SUCCESS";
  export const GET_TOOLOWNERS_EVENTS_FAILURE = "GET_TOOLOWNERS_EVENTS_FAILURE";

  export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
  export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
  export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

  export const GET_TOOLOWNERS_CATEGORY_REQUEST = "GET_TOOLOWNERS_CATEGORY_REQUEST";
  export const GET_TOOLOWNERS_CATEGORY_SUCCESS = "GET_TOOLOWNERS_CATEGORY_SUCCESS";
  export const GET_TOOLOWNERS_CATEGORY_FAILURE = "GET_TOOLOWNERS_CATEGORY_FAILURE";